### ISSUE TITLE
Week 04

### ISSUE THREAD

**Issue by jnaiman** [UIUC-iSchool-DataStories/is457_fall2024#1]
- [x] Random groups for Assignment #2
- [x] Announcement about groups for Assignment #2 sent.
- [x] Slides about Assignment #2?
- [x] Group contract for Assignment #2 + activity
- [x] Make GDS links for each group for the activity -- Specify which groups they should be using for this assignment!
     - [x] for A section (add Mutma + Kate as editors)
     - [x] for B section (add Xinhui + Kate + Christy as editors)
     - [x] make sure "allow adding folks from editors" allows editors to add folks as needed 
- [x] Data Sources slides
- [x] Data Sources brainstorm Miro board --> is this an in-class activity?
- [x] Extension requests for syllabus
- [x] Participation grades for this week?
